# Generated by Django 4.2.2 on 2023-06-25 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_contributors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=8192)),
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(choices=[('B', 'Bug'), ('I', 'Improvement'), ('T', 'Task')], max_length=1)),
                ('priority', models.CharField(choices=[('H', 'Hight'), ('M', 'Medium'), ('L', 'Low')], max_length=1)),
                ('status', models.CharField(choices=[('T', 'ToDo'), ('I', 'InProgress'), ('C', 'Closed')], max_length=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assignee_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_issues', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
        ),
    ]
